services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deer-flow-backend
    env_file:
      - .env
    environment:
      - SEARCH_API=${SEARCH_API:-tavily}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
    volumes:
      - ./conf.yaml:/app/conf.yaml
    ports:
      - "9050:8000"
    restart: unless-stopped
    networks:
      - deer-flow-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:9050/api}
        - NODE_ENV=production
        - SKIP_ENV_VALIDATION=true
    container_name: deer-flow-frontend
    ports:
      - "4051:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:9050/api}
      - NODE_ENV=production
      - SKIP_ENV_VALIDATION=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - deer-flow-network

networks:
  deer-flow-network:
    driver: bridge
